name: 'BPMN Exporter'
description: 'Export BPMN-models as SVG to a target directory'
author: 'SRF INTE'

inputs:
  sourceDirectory:
    description:
      'Directory where the BPMN-files are located. Extension has to be ".bpmn".'
    required: true
    default: 'src/main/resources/bpmn'
  targetDirectory:
    description: 'Directory where the SVG-files shall be exported'
    required: true
    default: 'src/main/resources/bpmn'

runs:
  using: node20
  main: dist/index.js
